# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 13:18
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=tinymce.models.HTMLField(default=1234),
            preserve_default=False,
        ),
    ]
